# Generated by Django 5.2.7 on 2025-11-30 14:26

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=myauth.models.user_avatar_directory_path,
            ),
        ),
    ]
