# Generated by Django 5.2.7 on 2025-10-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_orders_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="products",
            field=models.ManyToManyField(related_name="orders", to="shopapp.products"),
        ),
    ]
