# Generated by Django 5.2.7 on 2025-11-17 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_products_options_products_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="user",
            new_name="created_by",
        ),
    ]
