# Generated by Django 5.2.7 on 2025-11-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0009_alter_products_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="orders/receipts/"),
        ),
    ]
