# Generated by Django 5.2.7 on 2025-11-29 13:34

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0010_orders_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="preview",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=shopapp.models.product_preview_directory_path,
            ),
        ),
    ]
