# Generated by Django 5.2.7 on 2025-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0012_productimages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orders",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["name", "price"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
